# Generated by Django 4.2.18 on 2025-02-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='sigla',
            new_name='estado',
        ),
    ]
